### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
	"email": "sami@test.com",
	"name": "sami",
	"password": "112233",
	"password_confirmation": "112233"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "samialateya@hotmail.com",
	"password": "112233"
}


### logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExIiwiZW1haWwiOiJzYW1pYWxhdGV5YUBob3RtYWlsLmNvbSIsIm5hbWUiOiJzYW1pIiwiaWF0IjoxNjU1NTg5OTE5LCJleHAiOjE2NTU1OTM1MTl9.ZV3Xk_QUtKvPoXZ1fxySuhZWX342gCvua5li1M-ZcYI


### email verification
POST http://localhost:3000/auth/email-verification/send
Content-Type: application/json

{
	"email": "samialateya@hotmail.com"
}